### ISSUE TITLE
Can't find Load and Save state functions on 4.0 branch

### ISSUE THREAD

**Issue by Cronorobs** [paulloz/godot-ink#46]
Hello! 

First of all, thanks your work with this addon, I've been using it for some time in a game I'm making in Godot 3.5 and I'm really happy with it!

The thing is, with the release of Godot 4.0 I'm trying to migrate the game to this version, so I've downloaded the addon from the 4.0 branch, but seems like it has changed quite a bit. My game relies on the `LoadStateFromDisk` and `SaveStateOnDisk` functions, but I can't find them in `InkStory.cs` like on the 3.x version.

Are this functions already implemented? If not, is there any way to get this functionality from elsewhere on the addon? I see on the readme of the branch that this version is still under development, so no pressure, just want to know the current state of the development.

Thanks for your time and keep up the good work!

**Comment by paulloz** [comment]
Hey, those aren't implemented yet. I'll make sure to have those at the highest in the TODO list.

**Comment by Cronorobs** [comment]
Thank you very much, looking forward to it!

**Comment by paulloz** [comment]
Status report.  

There's a limitation in Godot 4 that prevents polymorphic methods to be accessed from `GDScript` (and, possibly, other scripting languages). This means for example I can't define the following and have both be callable outside C#.

```cs
public void LoadStateFile(FileAccess file)
{
    ...
}

public void LoadStateFile(string filePath)
{
    ...
}
```

Which I'm quite displeased with... Hoping this is going to be fixed in post 4.0 updates. If nothing else, I'll name those differently, but I don't like it. I'm letting this settle for a few days, to try and get info about the roadmap, before making a decision.

**Comment by Cronorobs** [comment]
Oh, that's quite inconvenient :( Godot 3 and the previous version of GDscript didn't have that problem, right?

**Comment by paulloz** [comment]
After talking with other Godot C# contributors, I'm just gonna name all of these differently (at the very least as a temporary version).

**Comment by paulloz** [comment]
New methods are accessible on the main branch, see #48 for the names. I'll document later 🙂

**Comment by Cronorobs** [comment]
Thank you so much! I just tried it and it's working like a charm! 

(I will check on future updates if the polymorphism error has been solved and you were able to rename the methods)
