### ISSUE TITLE
The type name 'VariableObserver' does not exist in the type 'Story'

### ISSUE THREAD

**Issue by CallumChaney** [paulloz/godot-ink#58]
**Describe the bug**
I am getting this error after following the quick-start guide:
...\godot\addons\GodotInk\Src\InkStory.cs(254,19): The type name 'VariableObserver' does not exist in the type 'Story'

**To Reproduce**
Follow quick-start guide, added first C# script
```C#
using Godot;
using GodotInk;
using System;

public partial class Story : VBoxContainer
{
	[Export]
	private InkStory story;
}
```
**Environment**
* OS: Windows
* Godot version: 4.1-mono
* godot-ink version: 1.0.0

**Comment by paulloz** [comment]
Hello,

You defined a class named `Story`, in the global namespace. It conflicts with the one in `Ink.Runtime`. I'll change how we reference this type to avoid this kind of thing, but since Godot addons are released as source files, this'll never be perfect.  
It is usually a good habit to use namespaces in your code.

**Comment by CallumChaney** [comment]
Of course just me being a idiot, trying to rush to get it to work and not thinking 😂. Thanks for the quick response

**Comment by paulloz** [comment]
I'm keeping this open, since I can at least mitigate the issue by fully qualifying everything.
